# surveyhub/docker-compose.yaml
services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: surveyuser
      POSTGRES_PASSWORD: totme
      POSTGRES_DB: surveyhub
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U surveyuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:  # Fixed: was "yamlweb"
    build: .
    command: >
      ./wait-for-posgres.sh db sh -c "python manage.py migrate --settings=surveyhub.settings.drd && python manage.py runserver 0.0.0.0:8000 --settings=surveyhub.settings.drd"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8001:8001"
      
    environment:
      #SECRET_KEY: ${SECRET_KEY}
      #DATABASE_URL: ${DATABASE_URL}
      #DJANGO_ENV_FILE: ${DJANGO_ENV_FILE:-.env.drd}
      #POSTGRES_USER: ${POSTGRES_USER}
      #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_DB=surveyhub
      - POSTGRES_USER=surveyuser
      - POSTGRES_PASSWORD=totme
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ${DJANGO_ENV_FILE:-.env.drd}

volumes:
  pgdata: