services:
  db:
    image: postgres:16
    container_name: surveyhub-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: surveyuser
      POSTGRES_PASSWORD: totme
      POSTGRES_DB: YOURDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: surveyhub-web
    command: gunicorn surveyhub.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data:
