# Generated by Django 5.2.3 on 2025-06-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_programmerresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmerresponse',
            name='interests',
        ),
        migrations.AddField(
            model_name='programmerresponse',
            name='favorite_areas',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
