# Generated by Django 5.2.3 on 2025-06-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_programmerresponse_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmerresponse',
            name='learning_other',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
